-- Seed: 50 common exercises across major muscle groups, three locales.
-- Re-runnable: matches on (name_en, is_custom=false).

insert into exercises (name_en, name_fr, name_ar, muscle_group, secondary_muscles, equipment) values
  ('Barbell Bench Press', 'Développé couché à la barre', 'بنش بريس بالبار', 'chest', '{shoulders,triceps}', 'barbell'),
  ('Incline Barbell Bench Press', 'Développé incliné à la barre', 'بنش بريس مائل بالبار', 'chest', '{shoulders,triceps}', 'barbell'),
  ('Dumbbell Bench Press', 'Développé couché aux haltères', 'بنش بريس بالدمبل', 'chest', '{shoulders,triceps}', 'dumbbell'),
  ('Incline Dumbbell Press', 'Développé incliné aux haltères', 'بنش بريس مائل بالدمبل', 'chest', '{shoulders,triceps}', 'dumbbell'),
  ('Push-Up', 'Pompes', 'تمرين الضغط', 'chest', '{shoulders,triceps,core}', 'bodyweight'),
  ('Dip', 'Dips', 'الديبس', 'chest', '{triceps,shoulders}', 'bodyweight'),
  ('Cable Fly', 'Écarté à la poulie', 'فتح بالكابل', 'chest', '{shoulders}', 'cable'),
  ('Pec Deck', 'Pec deck', 'بيك ديك', 'chest', '{shoulders}', 'machine'),
  ('Conventional Deadlift', 'Soulevé de terre', 'الديدليفت', 'back', '{legs,glutes,core}', 'barbell'),
  ('Barbell Row', 'Rowing barre', 'تجديف بالبار', 'back', '{arms,shoulders}', 'barbell'),
  ('Dumbbell Row', 'Rowing haltère', 'تجديف بالدمبل', 'back', '{arms,shoulders}', 'dumbbell'),
  ('Pull-Up', 'Tractions', 'العقلة', 'back', '{arms,shoulders}', 'bodyweight'),
  ('Lat Pulldown', 'Tirage vertical', 'سحب علوي', 'back', '{arms}', 'cable'),
  ('Seated Cable Row', 'Tirage horizontal assis', 'تجديف جالس بالكابل', 'back', '{arms,shoulders}', 'cable'),
  ('T-Bar Row', 'Rowing T-bar', 'تجديف تي-بار', 'back', '{arms,shoulders}', 'barbell'),
  ('Face Pull', 'Face pull', 'فيس بُل', 'shoulders', '{back}', 'cable'),
  ('Back Squat', 'Squat à la barre', 'سكوات بالبار', 'legs', '{glutes,core}', 'barbell'),
  ('Front Squat', 'Squat avant', 'سكوات أمامي', 'legs', '{glutes,core}', 'barbell'),
  ('Leg Press', 'Presse à cuisses', 'ضغط الأرجل', 'legs', '{glutes}', 'machine'),
  ('Walking Lunge', 'Fentes marchées', 'الاندفاع المتحرك', 'legs', '{glutes,core}', 'dumbbell'),
  ('Bulgarian Split Squat', 'Squat bulgare', 'سكوات بلغاري', 'legs', '{glutes}', 'dumbbell'),
  ('Leg Extension', 'Leg extension', 'تمديد الأرجل', 'legs', '{}', 'machine'),
  ('Romanian Deadlift', 'Soulevé de terre roumain', 'الديدليفت الروماني', 'legs', '{glutes,back}', 'barbell'),
  ('Lying Leg Curl', 'Leg curl allongé', 'ثني الأرجل مستلقياً', 'legs', '{glutes}', 'machine'),
  ('Hip Thrust', 'Hip thrust', 'هيب ثرست', 'glutes', '{legs}', 'barbell'),
  ('Glute Bridge', 'Pont fessier', 'جسر الأرداف', 'glutes', '{legs,core}', 'bodyweight'),
  ('Standing Calf Raise', 'Mollets debout', 'رفع الساق واقفاً', 'legs', '{}', 'machine'),
  ('Seated Calf Raise', 'Mollets assis', 'رفع الساق جالساً', 'legs', '{}', 'machine'),
  ('Overhead Press', 'Développé militaire', 'الضغط العلوي', 'shoulders', '{triceps,core}', 'barbell'),
  ('Dumbbell Shoulder Press', 'Développé épaules haltères', 'ضغط الكتف بالدمبل', 'shoulders', '{triceps}', 'dumbbell'),
  ('Lateral Raise', 'Élévations latérales', 'الرفرفة الجانبية', 'shoulders', '{}', 'dumbbell'),
  ('Rear Delt Fly', 'Oiseau', 'الرفرفة الخلفية', 'shoulders', '{back}', 'dumbbell'),
  ('Arnold Press', 'Développé Arnold', 'ضغط أرنولد', 'shoulders', '{triceps}', 'dumbbell'),
  ('Cable Lateral Raise', 'Élévations latérales poulie', 'رفرفة جانبية بالكابل', 'shoulders', '{}', 'cable'),
  ('Barbell Curl', 'Curl barre', 'بايسبس بالبار', 'arms', '{}', 'barbell'),
  ('Dumbbell Curl', 'Curl haltère', 'بايسبس بالدمبل', 'arms', '{}', 'dumbbell'),
  ('Hammer Curl', 'Curl marteau', 'بايسبس مطرقة', 'arms', '{}', 'dumbbell'),
  ('Preacher Curl', 'Curl pupitre', 'بايسبس بريتشر', 'arms', '{}', 'machine'),
  ('Cable Curl', 'Curl poulie', 'بايسبس بالكابل', 'arms', '{}', 'cable'),
  ('Triceps Pushdown', 'Extension triceps poulie', 'دفع التراي بالكابل', 'arms', '{}', 'cable'),
  ('Skull Crusher', 'Barre au front', 'كسر الجمجمة', 'arms', '{}', 'barbell'),
  ('Overhead Triceps Extension', 'Extension triceps au-dessus', 'تمديد التراي علوي', 'arms', '{}', 'dumbbell'),
  ('Close-Grip Bench Press', 'Développé prise serrée', 'بنش بقبضة ضيقة', 'arms', '{chest,shoulders}', 'barbell'),
  ('Triceps Dip', 'Dips triceps', 'ديبس التراي', 'arms', '{chest,shoulders}', 'bodyweight'),
  ('Plank', 'Planche', 'البلانك', 'core', '{shoulders}', 'bodyweight'),
  ('Hanging Leg Raise', 'Relevé de jambes suspendu', 'رفع الأرجل معلقاً', 'core', '{}', 'bodyweight'),
  ('Ab Wheel Rollout', 'Roue abdominale', 'عجلة البطن', 'core', '{shoulders}', 'bodyweight'),
  ('Cable Crunch', 'Crunch poulie', 'كرنش بالكابل', 'core', '{}', 'cable'),
  ('Russian Twist', 'Russian twist', 'التويست الروسي', 'core', '{}', 'bodyweight'),
  ('Kettlebell Swing', 'Swing kettlebell', 'سوينغ بالكيتل بل', 'fullBody', '{glutes,back,core}', 'kettlebell')
on conflict do nothing;
