-- Equipment scanner persistence + AI routine generator persistence.
-- Adds: user_saved_equipment, ai_generated_workouts, programs ai fields,
-- equipment-scans storage bucket, entitlement rules for the new features,
-- and a 30-day TTL cron for original scan images (mirrors D22 form-check pattern).

-- ---- user_saved_equipment -----------------------------------------------
create table if not exists user_saved_equipment (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  equipment_name text not null,
  equipment_data jsonb not null,
  scanned_image_url text,
  saved_at timestamptz not null default now()
);
create index if not exists use_user_saved_idx on user_saved_equipment (user_id, saved_at desc);
alter table user_saved_equipment enable row level security;
drop policy if exists use_self_all on user_saved_equipment;
create policy use_self_all on user_saved_equipment
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ---- ai_generated_workouts ----------------------------------------------
-- One-off workouts generated by ai-generate-workout. Distinct from the full
-- programs table because they are session-scoped, not multi-week structures.
create table if not exists ai_generated_workouts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  generated_at timestamptz not null default now(),
  input jsonb not null,
  output jsonb not null,
  reasoning text,
  was_used boolean not null default false,
  was_saved_as_template boolean not null default false,
  was_modified boolean not null default false
);
create index if not exists agw_user_gen_idx on ai_generated_workouts (user_id, generated_at desc);
alter table ai_generated_workouts enable row level security;
drop policy if exists agw_self_all on ai_generated_workouts;
create policy agw_self_all on ai_generated_workouts
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ---- programs ai fields -------------------------------------------------
alter table programs add column if not exists ai_reasoning text;
alter table programs add column if not exists generation_input jsonb;

-- ---- entitlement_rules: new feature rows --------------------------------
insert into entitlement_rules (feature, free_daily_limit, free_total_limit, premium_only, description) values
  ('equipment_scan',         5,    null, false, 'Equipment scanner — vision identification of gym equipment'),
  ('ai_workout_gen',         3,    null, false, 'AI single-workout generator (non-program)'),
  ('ai_program_gen',         null, null, true,  'AI multi-week program generator (premium)'),
  ('ai_program_regenerate',  null, null, true,  'Regenerate an in-preview AI program (premium, separate from initial gen)'),
  ('ai_exercise_alts',       10,   null, false, 'AI exercise-substitution suggestions'),
  ('ai_program_adjust',      null, null, true,  'Weekly program adjustment via AI')
on conflict (feature) do update set
  description = excluded.description,
  free_daily_limit = excluded.free_daily_limit,
  free_total_limit = excluded.free_total_limit,
  premium_only = excluded.premium_only;

-- ---- storage bucket: equipment-scans ------------------------------------
insert into storage.buckets (id, name, public)
values ('equipment-scans', 'equipment-scans', false)
on conflict (id) do nothing;

drop policy if exists es_owner_all on storage.objects;
create policy es_owner_all on storage.objects
  for all using (bucket_id = 'equipment-scans' and owner = auth.uid())
  with check (bucket_id = 'equipment-scans' and owner = auth.uid());

-- 30-day TTL: hard-delete scanned images and null out the URL on the
-- user_saved_equipment row (the equipment_data JSON is preserved so the
-- saved card still renders without the original photo).
do $$ begin
  perform cron.schedule(
    'sahha-equipment-scan-ttl',
    '15 3 * * *',
    $cmd$
      delete from storage.objects
      where bucket_id = 'equipment-scans'
        and created_at < now() - interval '30 days';
      update user_saved_equipment
        set scanned_image_url = null
        where scanned_image_url is not null
          and saved_at < now() - interval '30 days';
    $cmd$
  );
exception when others then null; end $$;
