-- Extend the global exercise library to 300+ entries.
-- Mirrors 0012 conventions: name_en/_fr/_ar required, instructions left null
-- (backfill in a later pass), is_custom = false, on conflict do nothing.
-- Adds difficulty + equipment_aliases for the equipment-scanner matcher.

-- Backfill new columns on the original 0012 seed to default difficulty.
update exercises set difficulty = coalesce(difficulty, 'intermediate')
  where is_custom = false and difficulty is null;

-- Common alias backfill for the original seed (helps the scanner's matcher).
update exercises set equipment_aliases = '{"flat bench","bench press"}'::text[]
  where name_en = 'Barbell Bench Press' and is_custom = false;
update exercises set equipment_aliases = '{"squat rack","power rack"}'::text[]
  where name_en in ('Back Squat','Front Squat') and is_custom = false;
update exercises set equipment_aliases = '{"smith"}'::text[]
  where name_en = 'Leg Press' and is_custom = false;
update exercises set equipment_aliases = '{"lat pulldown machine","pulldown"}'::text[]
  where name_en = 'Lat Pulldown' and is_custom = false;

insert into exercises (name_en, name_fr, name_ar, muscle_group, secondary_muscles, equipment, difficulty, equipment_aliases) values
  -- ---- CHEST (machine + cable + kettlebell + smith variants) ----
  ('Smith Machine Bench Press','Développé couché Smith','بنش سميث','chest','{shoulders,triceps}','machine','intermediate','{smith,bench}'),
  ('Machine Chest Press','Développé pectoraux machine','ضغط الصدر بالماكينة','chest','{shoulders,triceps}','machine','beginner','{plate-loaded chest press,hammer strength chest}'),
  ('Decline Barbell Bench Press','Développé décliné barre','بنش بريس مائل سفلي بالبار','chest','{triceps,shoulders}','barbell','intermediate','{decline bench}'),
  ('Decline Dumbbell Press','Développé décliné haltères','بنش بريس مائل سفلي بالدمبل','chest','{triceps,shoulders}','dumbbell','intermediate','{decline bench}'),
  ('Incline Cable Fly','Écarté incliné poulie','فتح مائل بالكابل','chest','{shoulders}','cable','intermediate','{cable crossover incline}'),
  ('Decline Cable Fly','Écarté décliné poulie','فتح مائل سفلي بالكابل','chest','{shoulders}','cable','intermediate','{cable crossover low}'),
  ('Cable Crossover','Cross-over poulie','كروس أوفر كابل','chest','{shoulders}','cable','intermediate','{cable cross}'),
  ('Dumbbell Fly','Écarté haltères','فتح بالدمبل','chest','{shoulders}','dumbbell','beginner','{}'),
  ('Svend Press','Svend press','سفيند بريس','chest','{shoulders}','dumbbell','beginner','{plate squeeze press}'),
  ('Landmine Press','Landmine press','لاند ماين بريس','chest','{shoulders,triceps}','barbell','intermediate','{landmine}'),
  ('Hex Press','Hex press','هكس بريس','chest','{triceps}','dumbbell','beginner','{crush press,squeeze press}'),
  ('Floor Press','Floor press','فلور بريس','chest','{triceps}','barbell','intermediate','{}'),
  ('Plyometric Push-Up','Pompe pliométrique','بوش أب بليومتري','chest','{shoulders,triceps}','bodyweight','advanced','{clap pushup}'),
  ('Diamond Push-Up','Pompe diamant','بوش أب الماس','chest','{triceps,shoulders}','bodyweight','intermediate','{}'),
  ('Archer Push-Up','Pompe archer','بوش أب الرامي','chest','{shoulders,triceps}','bodyweight','advanced','{}'),
  ('Ring Dip','Dip aux anneaux','ديبس على الحلق','chest','{triceps,shoulders}','bodyweight','advanced','{gymnastic rings}'),

  -- ---- BACK ----
  ('Pendlay Row','Rowing Pendlay','تجديف بندلاي','back','{arms,shoulders}','barbell','advanced','{}'),
  ('Yates Row','Rowing Yates','تجديف ييتس','back','{arms}','barbell','intermediate','{underhand row}'),
  ('Chest-Supported Row','Rowing buste appuyé','تجديف بسند الصدر','back','{arms,shoulders}','machine','beginner','{seal row,chest supported machine}'),
  ('Meadows Row','Rowing Meadows','تجديف ميدوز','back','{arms,shoulders}','barbell','advanced','{landmine row single arm}'),
  ('Inverted Row','Rowing inversé','تجديف مقلوب','back','{arms,shoulders,core}','bodyweight','beginner','{australian pullup,bar row}'),
  ('Chin-Up','Tractions supination','عقلة قبضة عكسية','back','{arms}','bodyweight','intermediate','{underhand pullup}'),
  ('Neutral-Grip Pull-Up','Tractions prise neutre','عقلة قبضة محايدة','back','{arms}','bodyweight','intermediate','{hammer grip pullup}'),
  ('Wide-Grip Pull-Up','Tractions prise large','عقلة قبضة عريضة','back','{shoulders}','bodyweight','advanced','{}'),
  ('Weighted Pull-Up','Tractions lestées','عقلة بوزن إضافي','back','{arms}','bodyweight','advanced','{belt pullup}'),
  ('Muscle-Up','Muscle-up','مسل أب','back','{arms,chest,shoulders}','bodyweight','advanced','{bar muscleup,ring muscleup}'),
  ('Single-Arm Lat Pulldown','Tirage unilatéral','سحب علوي بذراع واحدة','back','{arms}','cable','beginner','{single arm pulldown}'),
  ('Reverse-Grip Lat Pulldown','Tirage prise inversée','سحب علوي قبضة عكسية','back','{arms}','cable','beginner','{underhand pulldown}'),
  ('Wide-Grip Lat Pulldown','Tirage prise large','سحب علوي قبضة عريضة','back','{shoulders}','cable','beginner','{}'),
  ('Straight-Arm Pulldown','Tirage bras tendus','سحب بذراع مستقيمة','back','{shoulders,core}','cable','beginner','{stiff arm pulldown}'),
  ('Cable Pullover','Pullover poulie','بل أوفر كابل','back','{chest,shoulders}','cable','intermediate','{}'),
  ('Dumbbell Pullover','Pullover haltère','بل أوفر بالدمبل','back','{chest}','dumbbell','intermediate','{}'),
  ('Machine Row','Rowing machine','تجديف بالماكينة','back','{arms}','machine','beginner','{plate loaded row,hammer strength row}'),
  ('Smith Machine Row','Rowing Smith','تجديف بسميث','back','{arms,shoulders}','machine','intermediate','{smith bent row}'),
  ('Rack Pull','Rack pull','راك بُل','back','{glutes,arms}','barbell','intermediate','{partial deadlift,block pull}'),
  ('Snatch-Grip Deadlift','Soulevé prise large','ديدليفت قبضة عريضة','back','{legs,glutes}','barbell','advanced','{}'),
  ('Trap Bar Deadlift','Soulevé trap bar','ديدليفت تراب بار','back','{legs,glutes}','barbell','intermediate','{hex bar deadlift}'),
  ('Sumo Deadlift','Soulevé sumo','ديدليفت سومو','back','{legs,glutes}','barbell','intermediate','{}'),
  ('Single-Arm Dumbbell Row','Rowing haltère unilatéral','تجديف دمبل بذراع','back','{arms,shoulders}','dumbbell','beginner','{kroc row}'),
  ('Kroc Row','Kroc row','كروك رو','back','{arms,shoulders}','dumbbell','advanced','{heavy db row}'),
  ('Renegade Row','Rowing renégat','تجديف رينيغيد','back','{arms,core}','dumbbell','intermediate','{}'),
  ('Good Morning','Good morning','جود مورنينغ','back','{glutes,legs}','barbell','intermediate','{}'),
  ('Hyperextension','Hyperextension','هايبر إكستنشن','back','{glutes,legs}','machine','beginner','{45 degree back extension,roman chair}'),
  ('Reverse Hyper','Hyper inversé','هايبر معكوس','back','{glutes}','machine','intermediate','{}'),

  -- ---- SHOULDERS ----
  ('Push Press','Push press','بوش بريس','shoulders','{triceps,legs}','barbell','intermediate','{}'),
  ('Behind-the-Neck Press','Développé nuque','ضغط خلف الرقبة','shoulders','{triceps}','barbell','advanced','{}'),
  ('Seated Barbell Press','Développé assis barre','ضغط جالس بالبار','shoulders','{triceps}','barbell','intermediate','{}'),
  ('Seated Dumbbell Press','Développé assis haltères','ضغط جالس بالدمبل','shoulders','{triceps}','dumbbell','beginner','{}'),
  ('Machine Shoulder Press','Développé épaules machine','ضغط الكتف بالماكينة','shoulders','{triceps}','machine','beginner','{plate loaded shoulder press}'),
  ('Smith Shoulder Press','Développé épaules Smith','ضغط الكتف سميث','shoulders','{triceps}','machine','beginner','{}'),
  ('Landmine Shoulder Press','Landmine épaules','ضغط الكتف لاند ماين','shoulders','{triceps,core}','barbell','intermediate','{}'),
  ('Single-Arm Cable Lateral Raise','Élévation latérale unilatérale poulie','رفرفة جانبية بذراع واحدة','shoulders','{}','cable','beginner','{}'),
  ('Cable Front Raise','Élévation frontale poulie','رفع أمامي بالكابل','shoulders','{}','cable','beginner','{}'),
  ('Plate Front Raise','Élévation frontale disque','رفع أمامي بالقرص','shoulders','{}','barbell','beginner','{}'),
  ('Reverse Pec Deck','Pec deck inversé','بيك ديك معكوس','shoulders','{back}','machine','beginner','{rear delt machine}'),
  ('Cable Rear Delt Fly','Oiseau poulie','رفرفة خلفية بالكابل','shoulders','{back}','cable','beginner','{cable rear delt}'),
  ('Bent-Over Lateral Raise','Oiseau buste penché','رفرفة منحنية','shoulders','{back}','dumbbell','beginner','{}'),
  ('Upright Row','Tirage menton','تجديف عامودي','shoulders','{back,arms}','barbell','intermediate','{}'),
  ('Cable Upright Row','Tirage menton poulie','تجديف عامودي بالكابل','shoulders','{back,arms}','cable','beginner','{}'),
  ('Y-Raise','Y raise','رفع على شكل Y','shoulders','{back}','dumbbell','beginner','{}'),
  ('Dumbbell Z Press','Z press','زد بريس','shoulders','{core,triceps}','dumbbell','intermediate','{seated press no back support}'),
  ('Cuban Press','Cuban press','كوبان بريس','shoulders','{back}','dumbbell','intermediate','{}'),
  ('Handstand Push-Up','Pompes en équilibre','بوش أب وقوف على اليدين','shoulders','{triceps,core}','bodyweight','advanced','{wall handstand}'),
  ('Pike Push-Up','Pompe pike','بوش أب بايك','shoulders','{triceps}','bodyweight','intermediate','{}'),

  -- ---- ARMS (biceps + triceps + forearms) ----
  ('Concentration Curl','Curl concentration','كرل تركيز','arms','{}','dumbbell','beginner','{}'),
  ('Spider Curl','Curl spider','كرل سبايدر','arms','{}','dumbbell','beginner','{}'),
  ('Incline Dumbbell Curl','Curl incliné haltères','كرل مائل بالدمبل','arms','{}','dumbbell','beginner','{}'),
  ('Drag Curl','Curl drag','كرل دراغ','arms','{}','barbell','intermediate','{}'),
  ('Reverse Curl','Curl prise pronation','كرل عكسي','arms','{}','barbell','beginner','{}'),
  ('Zottman Curl','Curl Zottman','كرل زوتمان','arms','{}','dumbbell','intermediate','{}'),
  ('21s Curl','Curl 21s','كرل 21','arms','{}','barbell','intermediate','{twenty ones}'),
  ('Bayesian Curl','Curl bayésien','كرل بايزي','arms','{}','cable','intermediate','{behind body cable curl}'),
  ('Cable Hammer Curl','Curl marteau poulie','كرل مطرقة بالكابل','arms','{}','cable','beginner','{rope hammer curl}'),
  ('Machine Curl','Curl machine','كرل بالماكينة','arms','{}','machine','beginner','{biceps machine}'),
  ('Rope Pushdown','Extension corde','دفع التراي بالحبل','arms','{}','cable','beginner','{rope tricep pushdown}'),
  ('Reverse-Grip Pushdown','Extension prise inversée','دفع التراي قبضة عكسية','arms','{}','cable','beginner','{}'),
  ('Single-Arm Pushdown','Extension unilatérale','دفع التراي بذراع واحدة','arms','{}','cable','beginner','{}'),
  ('Tate Press','Tate press','تيت بريس','arms','{}','dumbbell','intermediate','{}'),
  ('JM Press','JM press','جي إم بريس','arms','{chest}','barbell','advanced','{}'),
  ('Bench Dip','Dips banc','ديبس على الكرسي','arms','{chest,shoulders}','bodyweight','beginner','{}'),
  ('Cable Overhead Triceps Extension','Extension triceps poulie','تمديد التراي علوي بالكابل','arms','{}','cable','beginner','{}'),
  ('Wrist Curl','Curl poignet','كرل الرسغ','arms','{}','dumbbell','beginner','{forearm curl}'),
  ('Reverse Wrist Curl','Curl poignet inversé','كرل الرسغ معكوس','arms','{}','dumbbell','beginner','{}'),
  ('Farmer Carry','Marche du fermier','مشية المزارع','arms','{core,back}','dumbbell','intermediate','{farmers walk}'),
  ('Plate Pinch','Pinch disque','ضغط القرص','arms','{}','barbell','intermediate','{plate pinch hold}'),
  ('Hammer Curl Cable','Curl marteau corde','كرل مطرقة بالحبل','arms','{}','cable','beginner','{}'),

  -- ---- LEGS (quads + hams) ----
  ('Hack Squat','Hack squat','هاك سكوات','legs','{glutes}','machine','intermediate','{plate loaded hack}'),
  ('Pendulum Squat','Squat pendulum','سكوات بندولوم','legs','{glutes}','machine','intermediate','{}'),
  ('Belt Squat','Belt squat','سكوات حزام','legs','{glutes}','machine','intermediate','{}'),
  ('Sissy Squat','Sissy squat','سيسي سكوات','legs','{}','bodyweight','advanced','{}'),
  ('Goblet Squat','Squat gobelet','سكوات غوبلت','legs','{glutes,core}','dumbbell','beginner','{kb goblet squat}'),
  ('Dumbbell Squat','Squat haltères','سكوات بالدمبل','legs','{glutes}','dumbbell','beginner','{}'),
  ('Smith Squat','Squat Smith','سكوات سميث','legs','{glutes}','machine','beginner','{}'),
  ('Pause Squat','Squat avec pause','سكوات مع توقف','legs','{glutes,core}','barbell','advanced','{}'),
  ('Box Squat','Box squat','بوكس سكوات','legs','{glutes}','barbell','intermediate','{}'),
  ('Zercher Squat','Zercher squat','زيرشر سكوات','legs','{core,glutes}','barbell','advanced','{}'),
  ('Overhead Squat','Squat au-dessus','سكوات علوي','legs','{shoulders,core}','barbell','advanced','{}'),
  ('Single-Leg Press','Presse à cuisses unilatérale','ضغط أرجل بساق واحدة','legs','{glutes}','machine','intermediate','{}'),
  ('Reverse Lunge','Fente arrière','اندفاع خلفي','legs','{glutes}','dumbbell','beginner','{}'),
  ('Forward Lunge','Fente avant','اندفاع أمامي','legs','{glutes}','dumbbell','beginner','{}'),
  ('Lateral Lunge','Fente latérale','اندفاع جانبي','legs','{glutes}','dumbbell','beginner','{cossack lunge}'),
  ('Curtsy Lunge','Fente arrière croisée','اندفاع متقاطع','legs','{glutes}','dumbbell','beginner','{}'),
  ('Step-Up','Montée sur banc','صعود الصندوق','legs','{glutes}','dumbbell','beginner','{box stepup}'),
  ('Pistol Squat','Squat pistolet','سكوات مسدس','legs','{glutes,core}','bodyweight','advanced','{single leg squat}'),
  ('Shrimp Squat','Shrimp squat','شريمب سكوات','legs','{glutes}','bodyweight','advanced','{}'),
  ('Trap Bar Romanian Deadlift','RDL trap bar','رومانيان ديدليفت تراب بار','legs','{glutes,back}','barbell','intermediate','{}'),
  ('Single-Leg Romanian Deadlift','RDL unilatéral','رومانيان ديدليفت بساق','legs','{glutes,back}','dumbbell','intermediate','{}'),
  ('Stiff-Leg Deadlift','Soulevé jambes tendues','ديدليفت رجل مستقيمة','legs','{glutes,back}','barbell','intermediate','{}'),
  ('Seated Leg Curl','Leg curl assis','ثني الأرجل جالساً','legs','{glutes}','machine','beginner','{}'),
  ('Standing Leg Curl','Leg curl debout','ثني الأرجل واقفاً','legs','{glutes}','machine','beginner','{single leg curl}'),
  ('Glute-Ham Raise','Glute-ham raise','رفع الأرداف والساق','legs','{glutes,back}','machine','advanced','{ghr}'),
  ('Nordic Hamstring Curl','Curl nordique','كرل نوردي','legs','{glutes}','bodyweight','advanced','{}'),
  ('Sled Push','Poussée traîneau','دفع الزحافة','legs','{glutes,core}','machine','intermediate','{prowler push}'),
  ('Sled Drag','Tirage traîneau','جر الزحافة','legs','{glutes,back}','machine','intermediate','{prowler drag}'),
  ('Jefferson Squat','Squat Jefferson','سكوات جيفرسون','legs','{glutes,core}','barbell','advanced','{}'),
  ('Cyclist Squat','Squat cycliste','سكوات الدراج','legs','{}','barbell','intermediate','{heels elevated squat}'),

  -- ---- GLUTES ----
  ('Single-Leg Hip Thrust','Hip thrust unilatéral','هيب ثرست بساق','glutes','{legs}','barbell','intermediate','{}'),
  ('B-Stance Hip Thrust','Hip thrust B-stance','هيب ثرست بي ستانس','glutes','{legs}','barbell','intermediate','{}'),
  ('Cable Pull-Through','Tirage poulie entre jambes','سحب بين الأرجل','glutes','{legs,back}','cable','beginner','{}'),
  ('Cable Kickback','Kickback poulie','ركلة خلفية بالكابل','glutes','{}','cable','beginner','{glute kickback}'),
  ('Machine Hip Abduction','Abducteurs machine','مباعدة الفخذ بالماكينة','glutes','{}','machine','beginner','{}'),
  ('Machine Hip Adduction','Adducteurs machine','تقريب الفخذ بالماكينة','glutes','{}','machine','beginner','{}'),
  ('Banded Lateral Walk','Marche latérale élastique','مشية جانبية بالمطاط','glutes','{}','bodyweight','beginner','{monster walk,lateral band walk}'),
  ('Frog Pump','Frog pump','فروغ بومب','glutes','{}','bodyweight','beginner','{}'),
  ('Donkey Kick','Donkey kick','ركلة الحمار','glutes','{}','bodyweight','beginner','{}'),
  ('Fire Hydrant','Fire hydrant','صنبور الحريق','glutes','{}','bodyweight','beginner','{}'),

  -- ---- CALVES ----
  ('Donkey Calf Raise','Mollets âne','رفع الساق على شكل حمار','legs','{}','machine','beginner','{}'),
  ('Single-Leg Calf Raise','Mollets unilatéral','رفع ساق واحدة','legs','{}','dumbbell','beginner','{}'),
  ('Smith Calf Raise','Mollets Smith','رفع الساق سميث','legs','{}','machine','beginner','{}'),
  ('Leg Press Calf Raise','Mollets presse','رفع الساق على ضغط الأرجل','legs','{}','machine','beginner','{}'),

  -- ---- CORE ----
  ('Cable Woodchopper','Bûcheron poulie','حطاب بالكابل','core','{shoulders}','cable','beginner','{}'),
  ('Cable Pallof Press','Pallof press poulie','بالوف بريس بالكابل','core','{}','cable','beginner','{anti rotation press}'),
  ('Dragon Flag','Drapeau du dragon','علم التنين','core','{}','bodyweight','advanced','{}'),
  ('L-Sit','L-sit','إل ست','core','{shoulders,arms}','bodyweight','advanced','{}'),
  ('V-Up','V-up','تمرين V','core','{}','bodyweight','intermediate','{}'),
  ('Toes-to-Bar','Toes to bar','الأصابع للبار','core','{back}','bodyweight','advanced','{t2b}'),
  ('Sit-Up','Abdo classique','جلوس البطن','core','{}','bodyweight','beginner','{situp}'),
  ('Decline Sit-Up','Abdo décliné','جلوس البطن مائل','core','{}','bodyweight','beginner','{}'),
  ('Side Plank','Planche latérale','بلانك جانبي','core','{shoulders}','bodyweight','beginner','{}'),
  ('Plank with Reach','Planche avec extension','بلانك مع تمديد','core','{shoulders}','bodyweight','intermediate','{}'),
  ('Mountain Climber','Grimpeur','تسلق الجبل','core','{shoulders}','bodyweight','beginner','{}'),
  ('Bicycle Crunch','Crunch vélo','كرنش دراجة','core','{}','bodyweight','beginner','{}'),
  ('Reverse Crunch','Crunch inversé','كرنش معكوس','core','{}','bodyweight','beginner','{}'),
  ('Hollow Body Hold','Hollow body','هولو بادي','core','{}','bodyweight','intermediate','{}'),
  ('Dead Bug','Dead bug','ديد باغ','core','{}','bodyweight','beginner','{}'),
  ('Bird Dog','Bird dog','بيرد دوغ','core','{back,glutes}','bodyweight','beginner','{}'),
  ('Hanging Knee Raise','Relevé genoux suspendu','رفع الركبتين معلقاً','core','{}','bodyweight','beginner','{}'),
  ('Windshield Wiper','Essuie-glace','مساحات السيارة','core','{}','bodyweight','advanced','{}'),
  ('Russian Twist Weighted','Russian twist lesté','تويست روسي مع وزن','core','{}','dumbbell','intermediate','{}'),
  ('Side Bend','Inclinaison latérale','انحناء جانبي','core','{}','dumbbell','beginner','{}'),
  ('Ab Rollout (Barbell)','Roue barre','عجلة البطن بالبار','core','{shoulders}','barbell','intermediate','{barbell rollout}'),

  -- ---- OLYMPIC + POWER ----
  ('Power Clean','Clean','كلين','fullBody','{legs,glutes,back,shoulders}','barbell','advanced','{olympic clean}'),
  ('Hang Clean','Hang clean','هانغ كلين','fullBody','{legs,glutes,back,shoulders}','barbell','advanced','{}'),
  ('Power Snatch','Snatch','سناتش','fullBody','{legs,glutes,back,shoulders}','barbell','advanced','{olympic snatch}'),
  ('Hang Snatch','Hang snatch','هانغ سناتش','fullBody','{legs,glutes,back,shoulders}','barbell','advanced','{}'),
  ('Push Jerk','Push jerk','بوش جيرك','fullBody','{shoulders,legs,triceps}','barbell','advanced','{}'),
  ('Split Jerk','Split jerk','سبليت جيرك','fullBody','{shoulders,legs,triceps}','barbell','advanced','{}'),
  ('Clean and Jerk','Épaulé jeté','كلين أند جيرك','fullBody','{legs,glutes,back,shoulders}','barbell','advanced','{c&j}'),
  ('Clean Pull','Clean pull','كلين بُل','fullBody','{back,legs,glutes}','barbell','advanced','{}'),
  ('Snatch Pull','Snatch pull','سناتش بُل','fullBody','{back,legs,glutes}','barbell','advanced','{}'),
  ('Thruster','Thruster','ثرستر','fullBody','{shoulders,legs,glutes}','barbell','intermediate','{}'),
  ('Wall Ball','Wall ball','وول بول','fullBody','{shoulders,legs,glutes,core}','bodyweight','intermediate','{medicine ball}'),
  ('Box Jump','Saut sur boîte','قفز الصندوق','legs','{glutes}','bodyweight','intermediate','{}'),
  ('Broad Jump','Saut horizontal','قفز أفقي','legs','{glutes}','bodyweight','intermediate','{long jump}'),
  ('Burpee','Burpee','بربي','fullBody','{chest,legs,core}','bodyweight','intermediate','{}'),
  ('Devil Press','Devil press','ديفل بريس','fullBody','{chest,shoulders,legs}','dumbbell','advanced','{}'),
  ('Man Maker','Man maker','مان ميكر','fullBody','{back,shoulders,legs}','dumbbell','advanced','{}'),
  ('Turkish Get-Up','Turkish get-up','الوقوف التركي','fullBody','{shoulders,core,legs}','kettlebell','advanced','{}'),
  ('Kettlebell Snatch','Snatch kettlebell','سناتش بالكيتل','fullBody','{back,shoulders,legs}','kettlebell','advanced','{}'),
  ('Kettlebell Clean','Clean kettlebell','كلين بالكيتل','fullBody','{back,legs,shoulders}','kettlebell','intermediate','{}'),
  ('Kettlebell Goblet Carry','Marche gobelet kettlebell','مشية غوبلت كيتل','fullBody','{core,arms}','kettlebell','beginner','{}'),

  -- ---- CARDIO + CONDITIONING ----
  ('Treadmill Run','Course tapis','جري على المشاية','fullBody','{legs}','machine','beginner','{treadmill}'),
  ('Treadmill Walk','Marche tapis','مشي على المشاية','fullBody','{legs}','machine','beginner','{}'),
  ('Incline Treadmill Walk','Marche inclinée','مشي مائل','fullBody','{legs,glutes}','machine','beginner','{12-3-30}'),
  ('Rowing Erg','Rameur','أيرغ التجديف','fullBody','{back,legs,arms,core}','machine','beginner','{rowing machine,concept2}'),
  ('Assault Bike','Vélo assaut','دراجة الهجوم','fullBody','{legs,arms}','machine','intermediate','{air bike,fan bike}'),
  ('Stationary Bike','Vélo stationnaire','دراجة ثابتة','fullBody','{legs}','machine','beginner','{exercise bike,spin bike}'),
  ('Stair Mill','Stair mill','ستير ميل','fullBody','{legs,glutes}','machine','beginner','{stairmaster}'),
  ('Ski Erg','Ski erg','سكي أيرغ','fullBody','{back,arms,core}','machine','intermediate','{}'),
  ('Jacobs Ladder','Échelle Jacobs','سلم جاكوب','fullBody','{legs,arms,core}','machine','intermediate','{}'),
  ('Jump Rope','Corde à sauter','حبل القفز','fullBody','{legs,shoulders}','bodyweight','beginner','{skipping rope}'),
  ('Battle Ropes','Cordes de combat','حبال المعركة','fullBody','{shoulders,arms,core}','cable','intermediate','{}'),
  ('Sprint','Sprint','سبرنت','fullBody','{legs,glutes}','bodyweight','intermediate','{running sprint}'),
  ('Hill Sprint','Sprint en côte','سبرنت في تلة','fullBody','{legs,glutes}','bodyweight','advanced','{}'),
  ('Sledgehammer Slam','Marteau pneu','مطرقة الإطار','fullBody','{shoulders,arms,core}','bodyweight','intermediate','{tire slam}'),
  ('Tire Flip','Renverser pneu','قلب الإطار','fullBody','{back,legs,glutes}','bodyweight','advanced','{}'),

  -- ---- CALISTHENICS / GYMNASTIC ----
  ('Front Lever','Front lever','فرونت ليفر','back','{core,arms}','bodyweight','advanced','{}'),
  ('Back Lever','Back lever','باك ليفر','back','{core,arms,chest}','bodyweight','advanced','{}'),
  ('Planche','Planche','بلانش','chest','{shoulders,core,arms}','bodyweight','advanced','{}'),
  ('Tuck Planche','Planche groupée','بلانش مجمع','chest','{shoulders,core,arms}','bodyweight','advanced','{}'),
  ('Human Flag','Drapeau humain','العلم البشري','core','{back,shoulders}','bodyweight','advanced','{}'),
  ('Skin the Cat','Skin the cat','سكين ذا كات','back','{shoulders,core}','bodyweight','advanced','{}'),
  ('Ring Push-Up','Pompe anneaux','بوش أب على الحلق','chest','{shoulders,triceps,core}','bodyweight','intermediate','{}'),
  ('Ring Row','Tirage anneaux','تجديف الحلق','back','{arms,shoulders}','bodyweight','intermediate','{ring inverted row}'),
  ('Archer Pull-Up','Archer pull-up','عقلة الرامي','back','{arms}','bodyweight','advanced','{}'),
  ('Typewriter Pull-Up','Tractions machine à écrire','عقلة الآلة الكاتبة','back','{arms}','bodyweight','advanced','{}'),
  ('Commando Pull-Up','Tractions commando','عقلة كوماندو','back','{arms,core}','bodyweight','advanced','{}'),

  -- ---- MOBILITY / WARM-UP ----
  ('Cat-Cow','Chat-vache','قطة-بقرة','core','{back}','bodyweight','beginner','{}'),
  ('World''s Greatest Stretch','Étirement complet','أفضل تمدد','fullBody','{}','bodyweight','beginner','{}'),
  ('90/90 Hip Stretch','Étirement 90/90','تمدد الورك 90/90','glutes','{}','bodyweight','beginner','{}'),
  ('Couch Stretch','Étirement canapé','تمدد الكنبة','legs','{}','bodyweight','beginner','{quad stretch}'),
  ('Hip Flexor Stretch','Étirement fléchisseurs','تمدد عاضلة الورك','legs','{}','bodyweight','beginner','{}'),
  ('Pigeon Pose','Position du pigeon','وضعية الحمامة','glutes','{}','bodyweight','beginner','{}'),
  ('Dead Hang','Suspension barre','تعليق على البار','back','{arms,core}','bodyweight','beginner','{bar hang}'),
  ('Banded Pull-Apart','Écartement bande','شد المطاط','shoulders','{back}','bodyweight','beginner','{band pullapart}'),
  ('Banded Face Pull','Face pull bande','فيس بُل بالمطاط','shoulders','{back}','bodyweight','beginner','{}'),
  ('Wall Slide','Glissade au mur','سلايد الحائط','shoulders','{back}','bodyweight','beginner','{}'),
  ('Scapular Pull-Up','Tractions scapulaires','عقلة لوح الكتف','back','{shoulders}','bodyweight','beginner','{scap pullup}'),
  ('Foam Roll Quads','Roller quadriceps','فرد العضلة الرباعية','legs','{}','bodyweight','beginner','{foam rolling}'),
  ('Foam Roll IT Band','Roller bande iliotibiale','فرد البند الجانبي','legs','{}','bodyweight','beginner','{}'),
  ('Thoracic Extension Roll','Extension thoracique roller','تمدد الصدري بالرولر','back','{}','bodyweight','beginner','{t-spine extension}'),

  -- ---- KETTLEBELL ----
  ('Kettlebell Goblet Squat','Goblet squat kettlebell','غوبلت سكوات بالكيتل','legs','{glutes,core}','kettlebell','beginner','{}'),
  ('Kettlebell Deadlift','Deadlift kettlebell','ديدليفت بالكيتل','back','{legs,glutes}','kettlebell','beginner','{}'),
  ('Kettlebell Press','Développé kettlebell','ضغط بالكيتل','shoulders','{triceps}','kettlebell','intermediate','{}'),
  ('Kettlebell Row','Rowing kettlebell','تجديف بالكيتل','back','{arms}','kettlebell','beginner','{}'),
  ('Kettlebell Halo','Halo kettlebell','هالو بالكيتل','shoulders','{core}','kettlebell','beginner','{}'),
  ('Kettlebell Windmill','Windmill kettlebell','وندميل بالكيتل','core','{shoulders,glutes}','kettlebell','intermediate','{}'),
  ('Single-Arm Kettlebell Swing','Swing kettlebell unilatéral','سوينغ بذراع واحدة','fullBody','{glutes,back,core}','kettlebell','intermediate','{}'),
  ('Kettlebell Figure 8','Kettlebell figure 8','الرقم 8 كيتل','core','{glutes}','kettlebell','beginner','{}'),

  -- ---- BANDS / MINIMAL ----
  ('Band Squat','Squat élastique','سكوات بالمطاط','legs','{glutes}','bodyweight','beginner','{resistance band squat}'),
  ('Band Row','Rowing élastique','تجديف بالمطاط','back','{arms}','bodyweight','beginner','{band row}'),
  ('Band Press','Développé élastique','ضغط بالمطاط','chest','{shoulders,triceps}','bodyweight','beginner','{band chest press}'),
  ('Band Lateral Raise','Élévation latérale élastique','رفرفة جانبية بالمطاط','shoulders','{}','bodyweight','beginner','{}'),
  ('Band Curl','Curl élastique','كرل بالمطاط','arms','{}','bodyweight','beginner','{}'),
  ('Band Pushdown','Extension élastique','دفع التراي بالمطاط','arms','{}','bodyweight','beginner','{}'),
  ('Band Good Morning','Good morning élastique','جود مورنينغ بالمطاط','back','{glutes,legs}','bodyweight','beginner','{}'),
  ('Band Pallof Press','Pallof press élastique','بالوف بريس بالمطاط','core','{}','bodyweight','beginner','{}'),

  -- ---- POWERLIFTING ACCESSORIES ----
  ('Pin Press','Pin press','بِن بريس','chest','{triceps,shoulders}','barbell','intermediate','{rack press}'),
  ('Slingshot Bench','Bench slingshot','بنش سلنغ شوت','chest','{triceps,shoulders}','barbell','intermediate','{}'),
  ('Larsen Press','Larsen press','لارسن بريس','chest','{triceps}','barbell','intermediate','{}'),
  ('Spoto Press','Spoto press','سبوتو بريس','chest','{triceps}','barbell','intermediate','{}'),
  ('Deficit Deadlift','Deadlift déficit','ديدليفت دفيسيت','back','{legs,glutes}','barbell','advanced','{}'),
  ('Block Pull','Block pull','بلوك بُل','back','{legs,glutes}','barbell','intermediate','{}'),
  ('Pause Deadlift','Deadlift avec pause','ديدليفت مع توقف','back','{legs,glutes}','barbell','advanced','{}'),
  ('Tempo Squat','Squat tempo','سكوات تيمبو','legs','{glutes}','barbell','intermediate','{3 second squat}'),
  ('Tempo Bench','Bench tempo','بنش تيمبو','chest','{triceps,shoulders}','barbell','intermediate','{}'),
  ('Anderson Squat','Anderson squat','أندرسون سكوات','legs','{glutes}','barbell','advanced','{dead start squat}')
on conflict do nothing;
